version: "3.7"
name: hotel-management-system
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - hotelsystem-net
    environment:
      MYSQL_DATABASE: hotelDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - hotelsystem-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/hotelDB?allowPublicKeyRetrieval=true
      - spring.datasource.password=admin
      - spring.datasource.username=admin
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2
networks:
  hotelsystem-net: